### ISSUE TITLE
서버API 관련해서 필요한거 모음

### ISSUE THREAD

**Issue by pes2013a** [aliwo/acleane#23]
1. swagger에 파라미터, 헤더 API 공개
2. 유저 post, delete 만들기
3. image get, delete 만들기\
4. 파라미터로 이름받아서 해당 유저가 있는지 없는지 반환하는 get 필요

**Comment by aliwo** [comment]
1. -> 
![image](https://user-images.githubusercontent.com/22769112/116783008-4d7a3300-aac7-11eb-8479-89fcbc84405c.png)

body 오른쪽의 header 사용하면 됩니당

**Comment by aliwo** [comment]
2. post 는 구글 로그인 하면 되구 delete (회원탈퇴)는 만들지 않습니다 ~
put 은 PUT users/me 로 만들었습니당~

**Comment by aliwo** [comment]
3. GET /image/{picture_id} 도 만들었습니당~

**Comment by aliwo** [comment]
4. GET /users/name/{name} 만들었습니당 available 이 false 면 중복된 닉네임이 있는거에여~
