### ISSUE TITLE
서버 API 수정했으면 하는거

### ISSUE THREAD

**Issue by pes2013a** [aliwo/acleane#27]
1. image 에 id필요 없음 날짜가 곧 id
2. put image필요
3. image get 할때 image_id말고 date로 get 할수 있으면
4. 테스트한다고 이미지 보내는데 자꾸 서버에 데이터가 쌓임

**Comment by aliwo** [comment]
지금 서버에서 내려가는 picture json 에는 date 정보가 없어영!
picture 를 생성할 때 date 를 업로드 하지 않으니까요
form data 에 date 컬럼 추가할까여?

-> 추가할 경우에는 date 값을 클라이언트에서 보내지 않을 경우 picture 생성이 안 되게 되요~

**Comment by aliwo** [comment]
4. picture 삭제도 만들겠습니다 ㅋ

**Comment by pes2013a** [comment]
네 id 대신에 date 추가하면 될 거 같아요

**Comment by aliwo** [comment]
id 는 필요해서 삭제는 안 합니당 그럼 date 추가할게여~

**Comment by aliwo** [comment]
혹시 한 날짜에 사진은 한 장으로 제한하고 있나요?

**Comment by aliwo** [comment]
http://52.78.107.248:8080/ui/#/default/api.rest.picture.upload_picture
수정 되었습니다~
한 날짜에 사진이 여러장 있을 경우 삭제는 id 로 해야 될 거 같아서 일단 삭제 api 는 id 를 사용해요~
